apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: loc

data:
  config.yml: |
    tunnel: f0856662-9396-4bf8-9a2b-fdd15cf83c88

    ingress:
      - hostname: lordofcricket.com
        service: http://nginx-ingress-controller.nginx-ingress.svc.cluster.local:80
        originRequest:
          httpHostHeader: lordofcricket.com

      - service: http_status:404