apiVersion: v1
kind: Service
metadata:
  name: loc-backend
  namespace: loc
spec:
  type: NodePort

  selector:
    app: loc-backend

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500